GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/658c61296777e8f2541f2151

###

POST http://localhost:3000/subscribers
Content-Type:  application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/658c61296777e8f2541f2151

###

Patch http://localhost:3000/subscribers/658c61296777e8f2541f2151
Content-Type: application/json

{
    "name": "New Name"
}